### ISSUE TITLE
consider name change to remove "rust" from name

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/semsimian#22]
In light of some possible policy changes in the Rust Foundation (see for example [here](https://news.ycombinator.com/item?id=35510987)), we maybe should consider changing the name of this package to remove the string "rust". There is a non-zero change that using "rust" in our name will cause problems

'rs' apparently is the preferred string to indicate a package is implemented in Rust (see [here](https://docs.google.com/document/d/1ErZlwz9bbSI43dNo-rgQdkovm2h5ycuW220mWSOAuok/edit))

so maybe rssim? (look like simrs is [taken](https://crates.io/crates/simrs))
h/t @iimpulse

**Comment by caufieldjh** [comment]
Uh. Wow, that's a bizarre policy. I'll save ranting for another forum.
Could we take a page from fastobo and call it fastsemsim? `fastsim` [is taken on pypi](https://pypi.org/project/fastsim/).

**Comment by justaddcoffee** [comment]
Sure, fastsemsim sounds fine to me

**Comment by caufieldjh** [comment]
https://fastsemsim.readthedocs.io/en/latest/

**Comment by justaddcoffee** [comment]
platypus!

**Comment by caufieldjh** [comment]
I'm on board with `platypus` if we can take over [this pypi name which hasn't been updated since 2014](https://pypi.org/project/Platypus/)

**Comment by justaddcoffee** [comment]
ah okay, it's taken

probably semsimrs or fastsim something more descriptive would be better anyway (as much as I love random animal names)

**Comment by caufieldjh** [comment]
semsimian?

**Comment by justaddcoffee** [comment]
> semsimian?

lol I like this one

**Comment by justaddcoffee** [comment]
Something tells me we should do this renaming sooner rather than later 

Related: we could use the sklearn trick of making [new rustsim package] a dependency of rustsim:
https://stackoverflow.com/questions/61363534/whats-the-recommended-way-of-renaming-a-project-in-pypi

**Comment by caufieldjh** [comment]
Package now on pypi: https://pypi.org/project/semsimian/
See redirect: https://pypi.org/project/rustsim/

**Comment by caufieldjh** [comment]
Complete
